# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: capsule-system
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - capsule-system
  selector:
    matchLabels:
      app.kubernetes.io/name: capsule
