{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "capsule.labels" . | nindent 4 }}
    {{- .Values.serviceMonitor.labels | toYaml | nindent 4 }}
  name: {{ include "capsule.fullname" . }}-monitor
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "capsule.labels" . | nindent 4 }}
      {{- .Values.serviceMonitor.matchLabels | toYaml | nindent 6 }}
{{- end }}