name: docker-ci

on:
  push:
    branches:
      - multiarch

jobs:
  docker-ci:
    runs-on: ubuntu-20.04
    steps:

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm

      -
        name: Set up Docker Buildx
        id: buildx
        with:
          install: true
        uses: docker/setup-buildx-action@v1

      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login to quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      -
        name: Build and push
        id: build-release
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            ptx96/capsule:latest
            quay.io/ptx96/capsule:latest

      -
        name: Image digest
        run: echo ${{ steps.build-release.outputs.digest }}
